### PR TITLE
Quick fix for a warning message

### PR DESCRIPTION
**Pull request by TwP**
Fixes a warning message by adding parenthesis around the assert method.

### CODE REVIEW

**Comment by look** [comment]
This looks good, but @elireisman already fixed it in his PR #176 which is waiting to be merged.

**Comment by TwP** [comment]
<sigh> of course its already fixed. I did open up another PR https://github.com/jlindsey/semantic/pull/31 to address the warnings coming from the semantic version library.

**Comment by elireisman** [comment]
Ha sorry, I should have split that fix into it's own separate PR. Also added a couple things to our `.gitignore` for the new debugging dev dependencies! Thanks for opening the semantic bug I saw that warning too.

**Comment by TwP** [comment]
Closing this out since the fix was merged into master via @elireisman's PR.

**Pull request closed without merging**
