### PR TITLE
Response body in the notifications payload

### PR DESCRIPTION
**Pull request by TwP**
I've found a need to access the response body in the notifications payload. I would like to measure the different between the request timing and the search time reported by ES in the response. The difference between the two timing values is the network latency.

/cc @grantr @dewski @shayfrendt

### CODE REVIEW

**Comment by grantr** [comment]
:+1:

**Comment by grantr** [comment]
Can we get a test or two in https://github.com/github/elastomer-client/blob/master/test/notifications_test.rb?

**Comment by TwP** [comment]
I'll throw in a version bump and cut a new gem release, too.

**Comment by dewski** [comment]
:+1:

**Pull request merged**
