### PR TITLE
[WIP] ES 2.X Compatibility

### PR DESCRIPTION
**Pull request by TwP**
This is a work in progress pull request to bring Elasticsearch 2.X compatibility to the elastomer-client codebase. The plan is to work through all the failing tests and iteratively fix issues until all the tests are green.

/cc @chrismwendt

### CODE REVIEW

**Comment by TwP** [comment]
All tests are passing against my local Elasticsearch 2.3.5 instance. Need to get some continuous integration running against an ES 2.X cluster.

@chrismwendt would you have time to put some :eyes: on this code and add comments where needed?

**Comment by chrismwendt** [comment]
Travis doesn't support multiple Elasticsearch versions (see https://github.com/thoughtbot/scenic/issues/110#issuecomment-167975782), so would it be OK to replace 1.x with 2.x in `.travis.yml`?

**Comment by TwP** [comment]
> would it be OK to replace 1.x with 2.x in `.travis.yml`?

That should be fine. Are we running the travis builds right now? I dont' see them reported in the "checks" for this PR at least.

**Comment by chrismwendt** [comment]
Looks good to go 🚀

**Comment by TwP** [comment]
:+1: I'll merge this in and then we can bump the version number and cut a new release via another PR

**Pull request merged**
